// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-NzAMkT6gZJxQ6vKBU3dDOoMcstSYvs',
    appId: '1:469338106281:web:fde353adabe30eefc9fcb8',
    messagingSenderId: '469338106281',
    projectId: 'transrent-35af1',
    authDomain: 'transrent-35af1.firebaseapp.com',
    storageBucket: 'transrent-35af1.appspot.com',
    measurementId: 'G-CHQQFSLWCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuDvRmQFuR4F3rhVR53Rk7rf-RfoKM2KU',
    appId: '1:469338106281:android:fc106566ca9c1326c9fcb8',
    messagingSenderId: '469338106281',
    projectId: 'transrent-35af1',
    storageBucket: 'transrent-35af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4g3yfC-5sRkocdfJqAM3TCFU5zLbmE3I',
    appId: '1:469338106281:ios:798d8e7649c7a003c9fcb8',
    messagingSenderId: '469338106281',
    projectId: 'transrent-35af1',
    storageBucket: 'transrent-35af1.appspot.com',
    iosBundleId: 'com.example.transrentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4g3yfC-5sRkocdfJqAM3TCFU5zLbmE3I',
    appId: '1:469338106281:ios:5e7f7895b90393fac9fcb8',
    messagingSenderId: '469338106281',
    projectId: 'transrent-35af1',
    storageBucket: 'transrent-35af1.appspot.com',
    iosBundleId: 'com.example.transrentApp.RunnerTests',
  );
}
